[package]
name = "loro_py"
version = "1.5.1-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "loro"
crate-type = ["cdylib"]

[dependencies]
# loro = { path = "../loro/crates/loro", features = ["counter", "jsonpath"] }
loro = { git = "https://github.com/loro-dev/loro.git", tag = "loro-ffi@1.5.0", features = [
    "counter",
    "jsonpath",
] }
fxhash = "0.2.1"
pyo3 = { version = "0.24.1" }
serde_json = "1"
