[package]
name = "loro_py"
version = "1.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "loro"
crate-type = ["cdylib"]

[dependencies]
# loro = { path = "../loro/crates/loro", features = ["counter", "jsonpath"] }
loro = { git = "https://github.com/loro-dev/loro.git", rev = "a168063460d73f5178bc28b00f067528566f6d48", features = [
    "counter",
    "jsonpath",
] }
fxhash = "0.2.1"
pyo3 = { version = "0.23.3" }
serde_json = "1"
