[package]
name = "loro_py"
version = "1.2.5-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "loro"
crate-type = ["cdylib", "rlib"]

[dependencies]
loro = { git = "https://github.com/loro-dev/loro.git", tag = "loro-crdt@1.2.5", features = [
    "counter",
    "jsonpath",
] }
loro-internal = { git = "https://github.com/loro-dev/loro.git", tag = "loro-crdt@1.2.5", features = [
    "counter",
    "jsonpath",
] }
fxhash = "0.2.1"
pyo3 = { version = "0.23.3" }
serde_json = "1"
